### ISSUE TITLE
how to extract parellel sentences

### ISSUE THREAD

**Issue by keyboardWitch** [FrancisGregoire/parSentExtract#1]
Hi, 
  I tried this scripts and trained a model  
  But  evel.py  is just evaluate the test data,how to extract parellel sentences ?
  could you provide some demo data ?
many thanks!

**Comment by FrancisGregoire** [comment]
An extract.py file has been added to extract sentence pairs from aligned articles. It works with files sharing the same filename with the source and target languages as file extensions. I provided few tokenized article pair examples in the samples directory.

**Comment by keyboardWitch** [comment]
Thanks  a lot , I will try it soon!

**Comment by imrrahul** [comment]
hyy anyone of you can help me , I am facing dificulty in executing . You can communicate with me on rahul.ranjan3012@gmail.com
