### ISSUE TITLE
Sample test.ref

### ISSUE THREAD

**Issue by luffycodes** [FrancisGregoire/parSentExtract#2]
Hey,

Can you please a provide a sample of test.ref or how should it look like?

thanks !

**Comment by FrancisGregoire** [comment]
The reference file is simply a text file containing the indices of the aligned parallel sentences (positive examples). Each row contains tab-delimited indices of a parallel source and target sentence pair. I added a test.ref file as an example in the samples directory. For example, sentences from rows 2, 4 and 6 are aligned, whereas the ones in rows 1, 3 and 5 are not aligned.

I hope it helps.

**Comment by luffycodes** [comment]
Thanks a lot ! Just one last question.. Does the indexing assume it starts from 1 in this file ?

**Comment by FrancisGregoire** [comment]
Sorry I should have added that 0 are not aligned. Indexing must starts at 0 to match Python's indexing. For example, 0 \tab 0 in test.ref means that the source/target sentences of the first row of test.src and test.trg are aligned.

**Comment by luffycodes** [comment]
Thanks ! Your code is very clean and nicely refactored.. thanks for uploading it :)

**Comment by luffycodes** [comment]
By any chance, do you happen to have trained checkpoints and corresponding source & target vocab? Just trying my luck !
I've been training the model since 12 hours and nearly reaching the end of third epoch. The paper mentions to run for 15 epochs.

**Comment by FrancisGregoire** [comment]
Are you running on GPU ? You can reduce state_size and embedding_size to 200. It dramatically reduces the training time and it slightly reduce the performance. I can send you vocabularies and a link to some checkpoint data by email if you want, but it's trained on English-French data.

**Comment by luffycodes** [comment]
Hey ! Yeah.. I'm training on a GPU ! 
If you could send the files, it would be great.. Email : ss164@rice.edu

**Comment by FrancisGregoire** [comment]
I sent you the files by email.
