### ISSUE TITLE
hello,dear FrancisGregoire

### ISSUE THREAD

**Issue by naginoa** [FrancisGregoire/parSentExtract#7]
Dear FrancisGregoire：
        Excuese me!It's my great honor to make a issue with you!
        I'm a senior student in china and now I have a project about sentence alignment. Eventually, I find this project on github, so I decide to use it to do something.Then, I devide my aligned comparable corpus into 3 parts as train_data, valid_data and test_data.Finally I find that I need vocabulary.source and vocabulary.target.  Can you help me introduce what these two are or What mistake did I make?I hope to receive your reply. Thank you!!!!

**Comment by naginoa** [comment]
can i extract sencence from en to ch(chinese) using this project?

**Comment by FrancisGregoire** [comment]
Sorry I was late to reply. Do you still need help regarding your questions? Please let me know. I will be happy to help.
